Clear screen but preserve text.

diff --git a/mpv-channel b/mpv-channel
--- a/mpv-channel
+++ b/mpv-channel
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Exit on error.
+set -e
+
 # Ensure dependencies are installed
 if ! command -v mpv > /dev/null 2>&1; then
     echo "mpv is not installed! Please install it to use this tool."
@@ -11,6 +14,18 @@ if ! command -v curl > /dev/null 2>&1; then
 fi
 
 while true; do
+    # Clear screen, but preserve all text currently on it, unlike clear
+    # command normally does.
+    # See: https://superuser.com/a/1667623
+    height="$(tput lines 2>/dev/null)"
+    if [ "$?" -eq 0 ]; then
+        until [ "$height" -le 1 ]; do
+            printf '\n'
+            height=$((height-1))
+        done
+    fi
+    command clear -x
+
     # Determine XDG-compliant config path
     if [ -z "$XDG_CONFIG_HOME" ]; then
         XDG_CONFIG_HOME="$HOME/.config"
@@ -109,9 +124,6 @@ while true; do
         if [[ "$RESPONSE" == "y" ]]; then
             rm -r $MPV_CHANNEL_SELECTOR_CONFIG_DIR
             echo "All configs have been removed!"
-
-            # Break here instead of continuing because we want all variables to reset too.
-            break
         else
             echo "Aborting..."
         fi
